language: dart

dart:
  - stable
  - 2.2.0

dart_task:
  - test
  
matrix:
  include:
    - dart: stable
      dart_task: analyzer

branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache