name: translit
description: Simple dart package for converting Cyrillic symbols to Translit and back
version: 1.0.5

homepage: https://github.com/alexeynobody/translit-dart

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:

dev_dependencies:
  test: ^1.9.4